lakh_midi_dbt:
  outputs:
    local:
      type: duckdb
      path: data/lakh_local.duckdb
      external_root: "data/silver_lakh_midi"
      threads: 1

    remote:
      type: duckdb
      path: data/lakh_remote.duckdb
      threads: 4

  target: local
