lakh_midi_dbt:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      external_root: "data/silver_lakh_midi"
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
