version: 2

sources:
  - name: bronze_data
    description: "Bronze layer data from Lakh MIDI Dataset pipeline"
    meta:
      external_location: "data/bronze_lakh_midi/{name}/*.parquet"
    tables:
      - name: raw_midi_files
        description: "Raw MIDI files extracted from lmd_full.tar.gz"
        columns:
          - name: file_path
            description: "Path to the MIDI file within the tar archive"
            data_type: varchar
          - name: midi_md5
            description: "MD5 hash of the MIDI file (extracted from filename)"
            data_type: varchar
          - name: file_content
            description: "Binary content of the MIDI file"
            data_type: blob
          - name: file_size_bytes
            description: "Size of the MIDI file in bytes"
            data_type: bigint
      
      - name: h5_extract
        description: "Extracted musicbrainz data from H5 files"
        columns:
          - name: track_id
            description: "Track ID from the H5 filename"
            data_type: varchar
          - name: file_path
            description: "Path to the H5 file within the tar archive"
            data_type: varchar
          - name: file_size_bytes
            description: "Size of the H5 file in bytes"
            data_type: bigint
          - name: analysis
            description: "Audio analysis data including bars, beats, sections, segments"
            data_type: struct
          - name: metadata
            description: "Artist and song metadata including terms, location, genre"
            data_type: struct
          - name: musicbrainz
            description: "MusicBrainz tags and year information"
            data_type: struct
      
      - name: raw_match_scores
        description: "Match scores between tracks and MIDI files"
        columns:
          - name: track_id
            description: "Track ID"
            data_type: varchar
          - name: midi_md5
            description: "MD5 hash of the matched MIDI file"
            data_type: varchar
          - name: match_score
            description: "Score indicating quality of the match"
            data_type: double
      
      - name: raw_md5_paths
        description: "Mapping of MD5 hashes to their source paths"
        columns:
          - name: midi_md5
            description: "MD5 hash of the MIDI file"
          - name: source_path
            description: "Original source path of the MIDI file"
          - name: path_order
            description: "Order of this path if multiple paths exist for same MD5"